server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staff/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://integrator-1570132.okta.com/oauth2/austjrxv6l4b9QEdT697
    audience: api://webserver
    client-id: 0oatjq2ezvvenZc6z697
    client-secret: QiDgljUqIfIVekp9nP_GlBW0rC6AxOHWtchDAqySai9cUWPt5S8h_zelcVpbu4eF
    scopes: openid, profile, email, offline_access







