server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_Hotel
    username: root
    password: 201189
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: HOTEL-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  config:
    import: optional:configserver:http://localhost:8885



okta:
  oauth2:
    issuer: https://integrator-1570132.okta.com/oauth2/austjrxv6l4b9QEdT697
    audience: api://webserver

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka