server:
  port: 8083


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices

  application:
    name: RATING-SERVICE


  config:
    import: optional:configserver:http://localhost:8885


#That's all filed are in ConfigServer(Github)
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://integrator-1570132.okta.com/oauth2/austjrxv6l4b9QEdT697
    audience: api://webserver